# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MyQuiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyQuiz
   pod 'AWAREFramework', '~> 1.12'
   pod 'AWAREFramework/MotionActivity', '~> 1.12'
   pod 'AWAREFramework/Microphone', '~> 1.12'
   pod 'AWAREFramework/HealthKit', '~> 1.12'
   
  target 'MyQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyQuizUITests' do
    # Pods for testing
  end

end
